### ISSUE TITLE
Checkin.js wont Minify

### ISSUE THREAD

**Issue by ColumbusGoClub** [ColumbusGoClub/ColumbusGoClub.github.io#2]
Shows attached error
![image](https://user-images.githubusercontent.com/18744550/46329786-a31f9380-c5dd-11e8-9a6e-8b6b0d8c75ee.png)

**Comment by SorenTheBrave** [comment]
The issue here is that I updated the file to use the new [ES6 javascript standard](https://en.wikipedia.org/wiki/ECMAScript#6th_Edition_-_ECMAScript_2015), which is fairly new. If you're using either the YUI javascript compressor or UglifyJS, then they won't succeed because they don't work with the new standard, so right now the tool to use is the Google Closure utility, which atom-minify says that it supports. I tried to configure it but honestly I couldn't figure out how to force Atom to do it. 

I'll keep trying to figure out how to enable it, but in the meantime I have run Closure on the file manually and have committed the minified version. It's now live on the site using that version.
